name: Generate contribution snake

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
  push:
    branches: [master, main]
    paths:
      - ".github/workflows/snake.yml"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Generate snakes
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            images/contributions.svg
            images/github-user-contribution.svg?palette=github-dark

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update contribution snake"
          file_pattern: images/contributions.svg images/github-user-contribution.svg
